name: "TagBot"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
jobs:
  tagbot:
    uses: "SciML/.github/.github/workflows/tagbot.yml@v1"
    secrets: "inherit"
  tagbot-subpackages:
    strategy:
      fail-fast: false
      matrix:
        subdir:
          - "lib/DelayDiffEq"
          - "lib/DiffEqBase"
          - "lib/DiffEqDevTools"
          - "lib/ImplicitDiscreteSolve"
          - "lib/OrdinaryDiffEqAdamsBashforthMoulton"
          - "lib/OrdinaryDiffEqAMF"
          - "lib/OrdinaryDiffEqBDF"
          - "lib/OrdinaryDiffEqCore"
          - "lib/OrdinaryDiffEqDefault"
          - "lib/OrdinaryDiffEqDifferentiation"
          - "lib/OrdinaryDiffEqExplicitRK"
          - "lib/OrdinaryDiffEqExplicitTableaus"
          - "lib/OrdinaryDiffEqExponentialRK"
          - "lib/OrdinaryDiffEqExtrapolation"
          - "lib/OrdinaryDiffEqFeagin"
          - "lib/OrdinaryDiffEqFIRK"
          - "lib/OrdinaryDiffEqFunctionMap"
          - "lib/OrdinaryDiffEqHighOrderRK"
          - "lib/OrdinaryDiffEqIMEXMultistep"
          - "lib/OrdinaryDiffEqImplicitTableaus"
          - "lib/OrdinaryDiffEqLinear"
          - "lib/OrdinaryDiffEqLowOrderRK"
          - "lib/OrdinaryDiffEqLowStorageRK"
          - "lib/OrdinaryDiffEqMultirate"
          - "lib/OrdinaryDiffEqNewmark"
          - "lib/OrdinaryDiffEqNonlinearSolve"
          - "lib/OrdinaryDiffEqNordsieck"
          - "lib/OrdinaryDiffEqPDIRK"
          - "lib/OrdinaryDiffEqPRK"
          - "lib/OrdinaryDiffEqQPRK"
          - "lib/OrdinaryDiffEqRKIP"
          - "lib/OrdinaryDiffEqRKN"
          - "lib/OrdinaryDiffEqRosenbrock"
          - "lib/OrdinaryDiffEqRosenbrockTableaus"
          - "lib/OrdinaryDiffEqSDIRK"
          - "lib/OrdinaryDiffEqSIMDRK"
          - "lib/OrdinaryDiffEqSSPRK"
          - "lib/OrdinaryDiffEqStabilizedIRK"
          - "lib/OrdinaryDiffEqStabilizedRK"
          - "lib/OrdinaryDiffEqSymplecticRK"
          - "lib/OrdinaryDiffEqTaylorSeries"
          - "lib/OrdinaryDiffEqTsit5"
          - "lib/OrdinaryDiffEqVerner"
          - "lib/SimpleImplicitDiscreteSolve"
          - "lib/StochasticDiffEq"
          - "lib/StochasticDiffEqCore"
          - "lib/StochasticDiffEqHighOrder"
          - "lib/StochasticDiffEqIIF"
          - "lib/StochasticDiffEqImplicit"
          - "lib/StochasticDiffEqLeaping"
          - "lib/StochasticDiffEqLevyArea"
          - "lib/StochasticDiffEqLowOrder"
          - "lib/StochasticDiffEqMilstein"
          - "lib/StochasticDiffEqROCK"
          - "lib/StochasticDiffEqRODE"
          - "lib/StochasticDiffEqWeak"
    uses: "SciML/.github/.github/workflows/tagbot.yml@v1"
    with:
      subdir: "${{ matrix.subdir }}"
    secrets: "inherit"
